spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bazoop
    username: bazoop
    password: root
    hikari:
      maximumPoolSize: 25
      connectionTimeout: 10000
      schema: public
      minimum-idle: 5
      idle-timeout: 120000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        type: trace
        ddl-auto: update
      generate-ddl: true

